name: my_quran_id
description: A new Flutter project.
publish_to: "none"
version: 1.3.2+8

environment:
  sdk: ">=3.8.1 <4.0.0"
dependencies:
  adhan: ^2.0.0+1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_timezone: ^4.1.0
  fluttertoast: ^8.2.12
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  hijriyah_indonesia: ^0.1.5
  intl: ^0.18.1
  intl_translation: ^0.18.2
  just_audio: ^0.9.46
  meta: ^1.9.1
  prayers_times: ^0.0.6
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.2

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/quran.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/images/
    - assets/datas/quran_data.json
    - assets/datas/surah/
    - assets/.env
  fonts:
    - family: Lpmq
      fonts:
        - asset: assets/fonts/lpmq_font.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_font.ttf
